### ISSUE TITLE
How to handle upload on laravel

### ISSUE THREAD

**Issue by saqueib** [overtrue/vue-avatar-cropper#12]
Thanks for the simple and powerful component, I just want to know how would I get the uploaded file at Laravel end. I have tried following but didn't work.

This how I used it

```js
<avatar-cropper
                @uploaded="updateUserAvatar"
                @uploading="handleUploading"
                trigger="#pick-avatar"
                :labels="labels"
                :upload-headers="{'X-Requested-With': 'XMLHttpRequest'}"
                upload-url="/avatar">
</avatar-cropper>

```

**Update**
It seems as soon as I crop then I get the following error, but If I upload an image without cropping it works 😕 

```
// Get the blob
$request->get('file');
```

```
// Get the file 
$request->file('file');

UploadedFile {#736
  -test: false
  -originalName: "blob"
  -mimeType: "application/octet-stream"
  -size: 0
  -error: 1
  #hashName: null
  path: ""
  filename: ""
  basename: ""
  pathname: ""
  extension: ""
  realPath: "/Volumes/connecticco/app/public"
  aTime: 1970-01-01 00:00:00
  mTime: 1970-01-01 00:00:00
  cTime: 1970-01-01 00:00:00
  inode: false
  size: false
  perms: 00
  owner: false
  group: false
  type: false
  writable: false
  readable: false
  executable: false
  file: false
  dir: false
  link: false
}
```

I am unable to upload it to php, please help

**Comment by overtrue** [comment]
Hi, @saqueib your uploaded is too big, http://php.net/manual/en/features.file-upload.errors.php

```
UPLOAD_ERR_INI_SIZE
Value: 1; The uploaded file exceeds the upload_max_filesize directive in php.ini.
```

You can check your upload result in Laravel: https://laravel.com/docs/5.6/requests#files

```php
if ($request->hasFile('photo')) {
    //
}
```

and you can get the upload error by [`getError`](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/File/UploadedFile.html#method_getError) API: 

```php
$request->file->getError(); 
```

If the upload was successful, the constant **UPLOAD_ERR_OK** is returned. Otherwise one of the other **UPLOAD_ERR_XXX** constants is returned.
