### ISSUE TITLE
当选择大文件时候,比如2-3MB的照片时候,就无法加载了

### ISSUE THREAD

**Issue by passioncsu** [overtrue/vue-avatar-cropper#14]
所以这个问题是不是必须得提前把图片设置小一点呢?有其他解决方案吗?

**Comment by wmcmurray** [comment]
I had this issue because my app is behind Nginx so if the file exceed maximum upload file size defined in the config, my API would return an Nginx html error page instead of a Json object and this project was not handling such case, so I added this in this pull request : #16 (precisely on that commit : https://github.com/overtrue/vue-avatar-cropper/pull/16/commits/4ad53d5699c5c31a819dff1d920f3e2fdb09920d )

**Comment by wuguojun1006** [comment]
文件后缀名这个问题还没解决掉吗？

**Comment by overtrue** [comment]
@wuguojun1006 请正确描述你的问题，以便于方便的解决。

**Comment by wuguojun1006** [comment]
图片裁剪提交后Request Payload中的 filename = "unknown"
